// ── Dictionnaire Emoji — Mode Lecture Visuel ─────────────────────────────────
// Forme exacte du mot (minuscules, sans ponctuation) → emoji
// Couvre : noms communs, verbes conjugués, adjectifs, pluriels, accords

const EMOJI_DICT = {

  // ── ÉMOTIONS & SENTIMENTS ─────────────────────────────────────────────────
  'aime': '❤️', 'aimes': '❤️', 'aime': '❤️', 'aimons': '❤️', 'aimez': '❤️', 'aiment': '❤️',
  'aimais': '❤️', 'aimait': '❤️', 'aimaient': '❤️', 'aimé': '❤️', 'aimée': '❤️',
  'aimait': '❤️', 'aimer': '❤️', 'aimera': '❤️', 'aimerait': '❤️',
  'amour': '❤️', 'amours': '❤️', 'amoureux': '😍', 'amoureuse': '😍',
  'joie': '😊', 'joyeux': '😊', 'joyeuse': '😊', 'joyeuses': '😊', 'joyeusement': '😊',
  'heureux': '😊', 'heureuse': '😊', 'heureuses': '😊', 'bonheur': '😊',
  'triste': '😢', 'tristes': '😢', 'tristesse': '😢', 'tristement': '😢',
  'pleure': '😢', 'pleures': '😢', 'pleurons': '😢', 'pleurez': '😢', 'pleurent': '😢',
  'pleurais': '😢', 'pleurait': '😢', 'pleurer': '😢', 'pleuré': '😢',
  'larme': '😢', 'larmes': '😢',
  'colère': '😡', 'colères': '😡', 'énervé': '😡', 'énervée': '😡',
  'fâché': '😡', 'fâchée': '😡', 'fâchés': '😡', 'furieux': '😡', 'furieuse': '😡',
  'peur': '😨', 'peurs': '😨', 'effrayé': '😨', 'effrayée': '😨', 'effrayés': '😨',
  'terrifié': '😨', 'terrifiée': '😨', 'terrifiant': '😨', 'terrifiante': '😨',
  'angoisse': '😰', 'angoisses': '😰', 'angoissé': '😰', 'angoissée': '😰',
  'inquiet': '😟', 'inquiète': '😟', 'inquiets': '😟', 'inquiètes': '😟',
  'surprise': '😲', 'surpris': '😲', 'surprises': '😲', 'étonné': '😲', 'étonnée': '😲',
  'honte': '😳', 'gêné': '😳', 'gêné': '😳', 'gênée': '😳', 'embarrassé': '😳',
  'fier': '😤', 'fière': '😤', 'fierté': '😤', 'orgueilleux': '😤',
  'ennui': '😴', 'ennuyeux': '😴', 'ennuyeuse': '😴', 'ennuyé': '😴',
  'solitude': '🥺', 'seul': '🥺', 'seule': '🥺', 'seuls': '🥺', 'seules': '🥺',
  'rire': '😂', 'rit': '😂', 'ris': '😂', 'rions': '😂', 'riez': '😂', 'rient': '😂',
  'riais': '😂', 'riait': '😂', 'ri': '😂', 'sourire': '😊', 'sourit': '😊',
  'sourire': '😊', 'souris': '😊', 'sourions': '😊', 'souriez': '😊', 'sourient': '😊',
  'espoir': '🌟', 'espère': '🌟', 'espères': '🌟', 'espérons': '🌟', 'espérez': '🌟',
  'espèrent': '🌟', 'espérer': '🌟',
  'confiance': '🤝', 'confiant': '🤝', 'confiante': '🤝',
  'jaloux': '😒', 'jalouse': '😒', 'jalousie': '😒',
  'haine': '💢', 'déteste': '💢', 'détestes': '💢', 'détestons': '💢', 'détestez': '💢',
  'détestent': '💢', 'haïr': '💢', 'hait': '💢',

  // ── CORPS HUMAIN ─────────────────────────────────────────────────────────
  'tête': '🧠', 'têtes': '🧠',
  'cerveau': '🧠', 'cerveaux': '🧠',
  'visage': '😶', 'visages': '😶', 'face': '😶',
  'oeil': '👁️', 'yeux': '👁️', 'regard': '👁️', 'regards': '👁️',
  'bouche': '👄', 'bouches': '👄', 'lèvre': '👄', 'lèvres': '👄',
  'nez': '👃', 'oreille': '👂', 'oreilles': '👂',
  'main': '✋', 'mains': '✋', 'poing': '✊', 'poings': '✊',
  'doigt': '👆', 'doigts': '👆', 'pouce': '👍', 'pouces': '👍',
  'bras': '💪', 'muscle': '💪', 'muscles': '💪', 'fort': '💪', 'forte': '💪',
  'jambe': '🦵', 'jambes': '🦵', 'pied': '🦶', 'pieds': '🦶',
  'coeur': '❤️', 'cœur': '❤️', 'coeurs': '❤️', 'cœurs': '❤️',
  'sang': '🩸', 'saigne': '🩸', 'saignes': '🩸', 'saignait': '🩸',
  'os': '🦴', 'squelette': '💀', 'crâne': '💀',
  'dent': '🦷', 'dents': '🦷',
  'cheveu': '💇', 'cheveux': '💇', 'chevelure': '💇',
  'ventre': '🤰', 'estomac': '🤢',
  'peau': '🫀', 'chair': '🫀', 'geste':'👋',

  // ── ACTIONS QUOTIDIENNES ─────────────────────────────────────────────────
  'mange': '🍽️', 'manges': '🍽️', 'mangeons': '🍽️', 'mangez': '🍽️', 'mangent': '🍽️',
  'mangeais': '🍽️', 'mangeait': '🍽️', 'manger': '🍽️', 'mangé': '🍽️',
  'boire': '🥤', 'boit': '🥤', 'bois': '🥤', 'buvons': '🥤', 'buvez': '🥤',
  'boivent': '🥤', 'buvais': '🥤', 'buvait': '🥤', 'bu': '🥤',
  'dort': '😴', 'dors': '😴', 'dormons': '😴', 'dormez': '😴', 'dorment': '😴',
  'dormais': '😴', 'dormait': '😴', 'dormir': '😴', 'dormi': '😴',
  'sommeil': '😴', 'rêve': '💭', 'rêves': '💭', 'rêvais': '💭', 'rêvait': '💭',
  'rêver': '💭', 'rêvé': '💭', 'rêvons': '💭',
  'marche': '🚶', 'marches': '🚶', 'marchons': '🚶', 'marchez': '🚶', 'marchent': '🚶',
  'marchais': '🚶', 'marchait': '🚶', 'marcher': '🚶', 'marché': '🚶',
  'court': '🏃', 'cours': '🏃', 'courons': '🏃', 'courez': '🏃', 'courent': '🏃',
  'courais': '🏃', 'courait': '🏃', 'courir': '🏃', 'couru': '🏃',
  'saute': '🦘', 'sautes': '🦘', 'sautons': '🦘', 'sautez': '🦘', 'sautent': '🦘',
  'nage': '🏊', 'nages': '🏊', 'nageons': '🏊', 'nagez': '🏊', 'nagent': '🏊',
  'vole': '✈️', 'voles': '✈️', 'volons': '✈️', 'volez': '✈️', 'volent': '✈️',
  'chante': '🎵', 'chantes': '🎵', 'chantons': '🎵', 'chantez': '🎵', 'chantent': '🎵',
  'chantais': '🎵', 'chantait': '🎵', 'chanter': '🎵', 'chanté': '🎵',
  'danse': '💃', 'danses': '💃', 'dansons': '💃', 'dansez': '💃', 'dansent': '💃',
  'dansais': '💃', 'dansait': '💃', 'danser': '💃', 'dansé': '💃',
  'parle': '💬', 'parles': '💬', 'parlons': '💬', 'parlez': '💬', 'parlent': '💬',
  'parlais': '💬', 'parlait': '💬', 'parler': '💬', 'parlé': '💬',
  'crie': '📢', 'cries': '📢', 'crions': '📢', 'criez': '📢', 'crient': '📢',
  'criais': '📢', 'criait': '📢', 'crier': '📢', 'crié': '📢',
  'chuchote': '🤫', 'chuchoter': '🤫', 'chuchoté': '🤫',
  'regarde': '👀', 'regardes': '👀', 'regardons': '👀', 'regardez': '👀', 'regardent': '👀',
  'regardais': '👀', 'regardait': '👀', 'regarder': '👀', 'regardé': '👀',
  'écoute': '👂', 'écoutes': '👂', 'écoutons': '👂', 'écoutez': '👂', 'écoutent': '👂',
  'écoutais': '👂', 'écoutait': '👂', 'écouter': '👂', 'écouté': '👂',
  'touche': '🤏', 'touches': '🤏', 'touchons': '🤏', 'touchez': '🤏', 'touchent': '🤏',
  'sent': '👃', 'sens': '👃', 'sentons': '👃', 'sentez': '👃', 'sentent': '👃',
  'sentais': '👃', 'sentait': '👃', 'sentir': '👃',
  'pense': '💭', 'penses': '💭', 'pensons': '💭', 'pensez': '💭', 'pensent': '💭',
  'pensais': '💭', 'pensait': '💭', 'penser': '💭', 'pensé': '💭',
  'sait': '🧠', 'sais': '🧠', 'savons': '🧠', 'savez': '🧠', 'savent': '🧠',
  'savais': '🧠', 'savait': '🧠', 'savoir': '🧠', 'su': '🧠',
  'comprend': '💡', 'comprends': '💡', 'comprenons': '💡', 'comprenez': '💡',
  'comprennent': '💡', 'compris': '💡', 'comprendre': '💡',
  'travaille': '💼', 'travailles': '💼', 'travaillons': '💼', 'travaillez': '💼',
  'travaillent': '💼', 'travaillais': '💼', 'travaillait': '💼', 'travailler': '💼',
  'construit': '🔨', 'construis': '🔨', 'construisons': '🔨', 'construisez': '🔨',
  'construisent': '🔨', 'construire': '🔨', 'construit': '🔨',
  'lit': '📖', 'lis': '📖', 'lisons': '📖', 'lisez': '📖', 'lisent': '📖',
  'lisais': '📖', 'lisait': '📖', 'lire': '📖', 'lu': '📖',
  'écrit': '✍️', 'écris': '✍️', 'écrivons': '✍️', 'écrivez': '✍️', 'écrivent': '✍️',
  'écrivais': '✍️', 'écrivait': '✍️', 'écrire': '✍️', 'écrit': '✍️',
  'dessine': '🎨', 'dessines': '🎨', 'dessinons': '🎨', 'dessinez': '🎨',
  'dessinent': '🎨', 'dessiner': '🎨', 'dessiné': '🎨',
  'joue': '🎮', 'joues': '🎮', 'jouons': '🎮', 'jouez': '🎮', 'jouent': '🎮',
  'jouais': '🎮', 'jouait': '🎮', 'jouer': '🎮', 'joué': '🎮',
  'cherche': '🔍', 'cherches': '🔍', 'cherchons': '🔍', 'cherchez': '🔍',
  'cherchent': '🔍', 'cherchais': '🔍', 'cherchait': '🔍', 'chercher': '🔍',
  'trouve': '🔍', 'trouves': '🔍', 'trouvons': '🔍', 'trouvez': '🔍', 'trouvent': '🔍',
  'trouvais': '🔍', 'trouvait': '🔍', 'trouver': '🔍', 'trouvé': '🔍',
  'cache': '🙈', 'caches': '🙈', 'cachons': '🙈', 'cachez': '🙈', 'cachent': '🙈',
  'caché': '🙈', 'cachée': '🙈', 'cachés': '🙈',
  'ouvre': '🚪', 'ouvres': '🚪', 'ouvrons': '🚪', 'ouvrez': '🚪', 'ouvrent': '🚪',
  'ouvrait': '🚪', 'ouvrir': '🚪', 'ouvert': '🚪', 'ouverte': '🚪',
  'ferme': '🔒', 'fermes': '🔒', 'fermons': '🔒', 'fermez': '🔒', 'ferment': '🔒',
  'fermais': '🔒', 'fermait': '🔒', 'fermer': '🔒', 'fermé': '🔒', 'fermée': '🔒',
  'tombe': '⬇️', 'tombes': '⬇️', 'tombons': '⬇️', 'tombez': '⬇️', 'tombent': '⬇️',
  'tombais': '⬇️', 'tombait': '⬇️', 'tomber': '⬇️', 'tombé': '⬇️',
  'lève': '🆙', 'lèves': '🆙', 'levons': '🆙', 'levez': '🆙', 'lèvent': '🆙',
  'levais': '🆙', 'levait': '🆙', 'lever': '🆙', 'levé': '🆙',
  'jette': '🗑️', 'jettes': '🗑️', 'jetons': '🗑️', 'jetez': '🗑️', 'jettent': '🗑️',
  'jetais': '🗑️', 'jetait': '🗑️', 'jeter': '🗑️', 'jeté': '🗑️',
  'attrape': '🤲', 'attrapes': '🤲', 'attrapons': '🤲', 'attrapez': '🤲',
  'attrapent': '🤲', 'attraper': '🤲', 'attrapé': '🤲',
  'frappe': '👊', 'frappes': '👊', 'frappons': '👊', 'frappez': '👊', 'frappent': '👊',
  'frappais': '👊', 'frappait': '👊', 'frapper': '👊', 'frappé': '👊',
  'embrasse': '🤗', 'embrasses': '🤗', 'embrassons': '🤗', 'embrassez': '🤗',
  'embrassent': '🤗', 'embrassait': '🤗', 'embrasser': '🤗', 'embrassé': '🤗',
  'serre': '🤗', 'serres': '🤗', 'serrons': '🤗', 'serrez': '🤗', 'serrent': '🤗',

  // ── NATURE ───────────────────────────────────────────────────────────────
  'soleil': '☀️', 'soleils': '☀️', 'ensoleillé': '☀️', 'ensoleillée': '☀️',
  'lune': '🌙', 'lunes': '🌙', 'lunaire': '🌙',
  'étoile': '⭐', 'étoiles': '⭐', 'étoilé': '⭐', 'étoilée': '⭐',
  'ciel': '🌤️', 'nuage': '☁️', 'nuages': '☁️', 'nuageux': '☁️', 'nuageuse': '☁️',
  'pluie': '🌧️', 'pleut': '🌧️', 'pluvieux': '🌧️', 'pluvieuse': '🌧️',
  'neige': '❄️', 'neiges': '❄️', 'neigeux': '❄️', 'neigeuse': '❄️', 'neiger': '❄️',
  'vent': '💨', 'vents': '💨', 'venteux': '💨', 'venteuse': '💨', 'souffle': '💨',
  'orage': '⛈️', 'orages': '⛈️', 'orageux': '⛈️', 'orageuse': '⛈️',
  'foudre': '⚡', 'tonnerre': '⛈️', 'éclair': '⚡', 'éclairs': '⚡',
  'feu': '🔥', 'feux': '🔥', 'flamme': '🔥', 'flammes': '🔥', 'brûle': '🔥',
  'brûler': '🔥', 'brûlé': '🔥', 'brûlait': '🔥', 'incendie': '🔥',
  'eau': '💧', 'eaux': '💧', 'rivière': '🏞️', 'rivières': '🏞️',
  'fleuve': '🌊', 'fleuves': '🌊', 'mer': '🌊', 'mers': '🌊', 'océan': '🌊',
  'vague': '🌊', 'vagues': '🌊', 'lac': '🏞️', 'lacs': '🏞️',
  'montagne': '⛰️', 'montagnes': '⛰️', 'colline': '🏔️', 'collines': '🏔️',
  'forêt': '🌲', 'forêts': '🌲', 'bois': '🌳', 'arbre': '🌳', 'arbres': '🌳',
  'fleur': '🌸', 'fleurs': '🌸', 'rose': '🌹', 'roses': '🌹',
  'herbe': '🌿', 'prairie': '🌾', 'champ': '🌾', 'champs': '🌾',
  'désert': '🏜️', 'déserts': '🏜️', 'sable': '🏖️', 'sables': '🏖️',
  'terre': '🌍', 'sol': '🌍', 'pierre': '🪨', 'pierres': '🪨', 'rocher': '🪨',
  'caverne': '🕳️', 'grotte': '🕳️', 'grottes': '🕳️',
  'île': '🏝️', 'îles': '🏝️',
  'volcan': '🌋', 'volcans': '🌋',
  'arc-en-ciel': '🌈',
  'brouillard': '🌫️', 'brume': '🌫️', 'brumeux': '🌫️', 'brumeuse': '🌫️',
  'givre': '🧊', 'gel': '🧊', 'glace': '🧊', 'glacier': '🧊',

  // ── ANIMAUX ───────────────────────────────────────────────────────────────
  'chien': '🐕', 'chiens': '🐕', 'chienne': '🐕', 'chiennes': '🐕',
  'chat': '🐈', 'chats': '🐈', 'chatte': '🐈', 'chattes': '🐈',
  'cheval': '🐴', 'chevaux': '🐴', 'jument': '🐴', 'poulain': '🐴',
  'oiseau': '🐦', 'oiseaux': '🐦', 'aigle': '🦅', 'aigles': '🦅',
  'corbeau': '🐦‍⬛', 'corbeaux': '🐦‍⬛', 'colombe': '🕊️', 'colombes': '🕊️',
  'loup': '🐺', 'loups': '🐺', 'louve': '🐺', 'louves': '🐺',
  'renard': '🦊', 'renards': '🦊', 'renarde': '🦊',
  'cerf': '🦌', 'cerfs': '🦌', 'biche': '🦌', 'biches': '🦌',
  'ours': '🐻', 'serpent': '🐍', 'serpents': '🐍',
  'lion': '🦁', 'lions': '🦁', 'lionne': '🦁', 'lionnes': '🦁',
  'tigre': '🐯', 'tigres': '🐯', 'tigresse': '🐯',
  'éléphant': '🐘', 'éléphants': '🐘',
  'singe': '🐒', 'singes': '🐒',
  'poisson': '🐟', 'poissons': '🐟', 'requin': '🦈', 'requins': '🦈',
  'araignée': '🕷️', 'araignées': '🕷️', 'insecte': '🐛', 'insectes': '🐛',
  'papillon': '🦋', 'papillons': '🦋', 'abeille': '🐝', 'abeilles': '🐝',
  'souris': '🐭', 'rat': '🐀', 'rats': '🐀',
  'lapin': '🐰', 'lapins': '🐰', 'lapine': '🐰',
  'vache': '🐄', 'vaches': '🐄', 'mouton': '🐑', 'moutons': '🐑',
  'cochon': '🐷', 'cochons': '🐷', 'poule': '🐔', 'poules': '🐔',
  'dragon': '🐉', 'dragons': '🐉',
  'monstre': '👾', 'monstres': '👾',
  'fantôme': '👻', 'fantômes': '👻',

  // ── NOURRITURE & BOISSONS ────────────────────────────────────────────────
  'pain': '🍞', 'pains': '🍞', 'boulangerie': '🥖',
  'viande': '🥩', 'viandes': '🥩', 'steak': '🥩',
  'poisson': '🐟', 'fruit': '🍎', 'fruits': '🍎',
  'pomme': '🍎', 'pommes': '🍎', 'poire': '🍐', 'poires': '🍐',
  'raisin': '🍇', 'raisins': '🍇', 'fraise': '🍓', 'fraises': '🍓',
  'citron': '🍋', 'citrons': '🍋', 'orange': '🍊', 'oranges': '🍊',
  'banane': '🍌', 'bananes': '🍌',
  'légume': '🥦', 'légumes': '🥦', 'carotte': '🥕', 'carottes': '🥕',
  'tomate': '🍅', 'tomates': '🍅', 'salade': '🥗', 'salades': '🥗',
  'soupe': '🍲', 'soupes': '🍲', 'fromage': '🧀', 'fromages': '🧀',
  'oeuf': '🥚', 'oeufs': '🥚', 'œuf': '🥚', 'œufs': '🥚',
  'gâteau': '🎂', 'gâteaux': '🎂', 'chocolat': '🍫', 'bonbon': '🍬', 'bonbons': '🍬',
  'glace': '🍦', 'crème': '🍦',
  'café': '☕', 'thé': '🍵', 'lait': '🥛',
  'vin': '🍷', 'vins': '🍷', 'bière': '🍺', 'bières': '🍺',
  'eau': '💧', 'jus': '🧃',
  'repas': '🍽️', 'dîner': '🍽️', 'déjeuner': '🍽️', 'petit-déjeuner': '🍳',
  'cuisine': '👨‍🍳', 'cuisiner': '👨‍🍳', 'cuisinait': '👨‍🍳', 'cuisiné': '👨‍🍳',

  // ── TRANSPORT ────────────────────────────────────────────────────────────
  'voiture': '🚗', 'voitures': '🚗', 'automobile': '🚗', 'automobiles': '🚗',
  'camion': '🚚', 'camions': '🚚', 'bus': '🚌', 'autobus': '🚌',
  'train': '🚂', 'trains': '🚂', 'locomotive': '🚂',
  'avion': '✈️', 'avions': '✈️', 'aéroport': '✈️',
  'bateau': '⛵', 'bateaux': '⛵', 'navire': '🚢', 'navires': '🚢',
  'vélo': '🚲', 'vélos': '🚲', 'bicyclette': '🚲',
  'moto': '🏍️', 'motos': '🏍️', 'motocyclette': '🏍️',
  'fusée': '🚀', 'fusées': '🚀', 'vaisseau': '🚀',
  'route': '🛣️', 'routes': '🛣️', 'chemin': '🛤️', 'chemins': '🛤️',
  'pont': '🌉', 'ponts': '🌉',
  'voyage': '✈️', 'voyages': '✈️', 'voyager': '✈️', 'voyagé': '✈️',
  'voyageais': '✈️', 'voyageait': '✈️',

  // ── LIEUX & BÂTIMENTS ────────────────────────────────────────────────────
  'maison': '🏠', 'maisons': '🏠', 'demeure': '🏠', 'demeures': '🏠',
  'château': '🏰', 'châteaux': '🏰', 'palais': '🏰',
  'cabane': '🛖', 'cabanes': '🛖', 'chaumière': '🛖',
  'ville': '🏙️', 'villes': '🏙️', 'cité': '🏙️', 'cités': '🏙️',
  'village': '🏘️', 'villages': '🏘️',
  'école': '🏫', 'écoles': '🏫', 'université': '🎓', 'universités': '🎓',
  'bibliothèque': '📚', 'bibliothèques': '📚',
  'hôpital': '🏥', 'hôpitaux': '🏥',
  'église': '⛪', 'églises': '⛪', 'temple': '🛕', 'temples': '🛕',
  'prison': '🏛️', 'prisons': '🏛️',
  'marché': '🏪', 'marchés': '🏪', 'magasin': '🏪', 'magasins': '🏪',
  'restaurant': '🍴', 'restaurants': '🍴',
  'hôtel': '🏨', 'hôtels': '🏨',
  'jardin': '🌻', 'jardins': '🌻', 'parc': '🌳', 'parcs': '🌳',
  'porte': '🚪', 'portes': '🚪', 'fenêtre': '🪟', 'fenêtres': '🪟',
  'escalier': '🪜', 'escaliers': '🪜', 'couloir': '🚶',
  'chambre': '🛏️', 'chambres': '🛏️', 'lit': '🛏️', 'lits': '🛏️',
  'cuisine': '🍳', 'salle': '🚿',
  'cave': '🕳️', 'caves': '🕳️', 'grenier': '🏚️',
  'tour': '🗼', 'tours': '🗼', 'mur': '🧱', 'murs': '🧱',

  // ── TEMPS ────────────────────────────────────────────────────────────────
  'matin': '🌅', 'matins': '🌅', 'aurore': '🌅', 'aube': '🌅',
  'midi': '☀️', 'après-midi': '🌤️',
  'soir': '🌆', 'soirs': '🌆', 'soirée': '🌆', 'soirées': '🌆',
  'nuit': '🌙', 'nuits': '🌙', 'minuit': '🌙',
  'jour': '📅', 'jours': '📅', 'journée': '📅', 'journées': '📅',
  'semaine': '📅', 'semaines': '📅', 'mois': '📅', 'année': '📅', 'années': '📅',
  'printemps': '🌸', 'été': '☀️', 'automne': '🍂', 'hiver': '❄️',
  'hier': '⏮️', 'demain': '⏭️', 'maintenant': '⏱️', 'toujours': '♾️',
  'jamais': '❌', 'parfois': '🔄', 'souvent': '🔄',
  'horloge': '🕐', 'horloges': '🕐', 'montre': '⌚', 'montres': '⌚',
  'heure': '🕐', 'heures': '🕐', 'minute': '⏱️', 'minutes': '⏱️',

  // ── RELATIONS SOCIALES ───────────────────────────────────────────────────
  'ami': '👫', 'amie': '👫', 'amis': '👫', 'amies': '👫', 'amitié': '👫',
  'ennemi': '⚔️', 'ennemie': '⚔️', 'ennemis': '⚔️', 'ennemies': '⚔️',
  'famille': '👨‍👩‍👧', 'familles': '👨‍👩‍👧',
  'père': '👨', 'pères': '👨', 'papa': '👨',
  'mère': '👩', 'mères': '👩', 'maman': '👩',
  'frère': '👦', 'frères': '👦', 'soeur': '👧', 'sœur': '👧', 'sœurs': '👧',
  'fils': '👦', 'fille': '👧', 'filles': '👧', 'enfant': '👶', 'enfants': '👶',
  'bébé': '👶', 'bébés': '👶',
  'grand-père': '👴', 'grand-mère': '👵', 'grands-parents': '👴',
  'roi': '👑', 'rois': '👑', 'reine': '👑', 'reines': '👑',
  'prince': '🤴', 'princes': '🤴', 'princesse': '👸', 'princesses': '👸',
  'soldat': '💂', 'soldats': '💂', 'guerrier': '⚔️', 'guerriers': '⚔️',
  'héros': '🦸', 'héroïne': '🦸', 'sauveur': '🦸',
  'monstre': '👾', 'méchant': '😈', 'méchante': '😈', 'méchants': '😈',
  'fantôme': '👻', 'sorcière': '🧙', 'sorcières': '🧙', 'sorcier': '🧙',
  'magicien': '🧙', 'magicienne': '🧙',
  'médecin': '👨‍⚕️', 'médecins': '👨‍⚕️', 'docteur': '👨‍⚕️',
  'mariage': '💒', 'marié': '💒', 'mariée': '💒', 'mariés': '💒',
  'mort': '💀', 'morte': '💀', 'morts': '💀', 'mortes': '💀', 'mourir': '💀',
  'meurt': '💀', 'mourut': '💀', 'mourait': '💀', 'mort': '💀',
  'naissance': '👶', 'naît': '👶', 'né': '👶', 'née': '👶',

  // ── OBJETS QUOTIDIENS ────────────────────────────────────────────────────
  'livre': '📖', 'livres': '📖', 'roman': '📖', 'romans': '📖',
  'lettre': '📜', 'lettres': '📜', 'message': '💬', 'messages': '💬',
  'clé': '🔑', 'clés': '🔑', 'clef': '🔑', 'clefs': '🔑',
  'épée': '⚔️', 'épées': '⚔️', 'couteau': '🔪', 'couteaux': '🔪',
  'arc': '🏹', 'flèche': '🏹', 'flèches': '🏹',
  'bouclier': '🛡️', 'boucliers': '🛡️', 'armure': '🛡️', 'armures': '🛡️',
  'couronne': '👑', 'couronnes': '👑',
  'trésor': '💎', 'trésors': '💎', 'or': '💰', 'argent': '💰',
  'pièce': '🪙', 'pièces': '🪙',
  'lampe': '💡', 'lampes': '💡', 'bougie': '🕯️', 'bougies': '🕯️',
  'feu': '🔥', 'torche': '🔦', 'torches': '🔦',
  'carte': '🗺️', 'cartes': '🗺️', 'boussole': '🧭',
  'sac': '🎒', 'sacs': '🎒',
  'vêtement': '👗', 'vêtements': '👗', 'robe': '👗', 'robes': '👗',
  'manteau': '🧥', 'manteaux': '🧥', 'chapeau': '🎩', 'chapeaux': '🎩',
  'bague': '💍', 'bagues': '💍', 'collier': '📿', 'colliers': '📿',
  'miroir': '🪞', 'miroirs': '🪞',
  'horloge': '🕐', 'pendule': '🕰️',
  'médaille': '🏅', 'médailles': '🏅', 'trophée': '🏆', 'trophées': '🏆',
  'téléphone': '📱', 'téléphones': '📱',
  'ordinateur': '💻', 'ordinateurs': '💻',

  // ── LUMIÈRE & OBSCURITÉ ──────────────────────────────────────────────────
  'lumière': '💡', 'lumières': '💡', 'lumineux': '💡', 'lumineuse': '💡',
  'sombre': '🌑', 'obscur': '🌑', 'obscurité': '🌑', 'ombre': '🌑', 'ombres': '🌑',
  'noir': '⬛', 'noire': '⬛', 'noirs': '⬛', 'noires': '⬛', 'noirceur': '⬛',
  'blanc': '⬜', 'blanche': '⬜', 'blancs': '⬜', 'blanches': '⬜',
  'rouge': '🔴', 'rouges': '🔴', 'rougeur': '🔴',
  'bleu': '🔵', 'bleue': '🔵', 'bleus': '🔵', 'bleues': '🔵',
  'vert': '🟢', 'verte': '🟢', 'verts': '🟢', 'vertes': '🟢',
  'jaune': '🟡', 'jaunes': '🟡', 'or': '🟡',
  'brillant': '✨', 'brillante': '✨', 'brillants': '✨', 'brille': '✨',
  'scintille': '✨', 'étincelle': '✨', 'étincelles': '✨',

  // ── CONCEPTS ABSTRAITS ───────────────────────────────────────────────────
  'vie': '🌱', 'vies': '🌱', 'vivant': '🌱', 'vivante': '🌱',
  'mort': '💀', 'destin': '🎯', 'destins': '🎯',
  'magie': '✨', 'magique': '✨', 'sort': '🪄', 'sorts': '🪄', 'charme': '🪄',
  'mystère': '🔮', 'mystères': '🔮', 'mystérieux': '🔮', 'mystérieuse': '🔮',
  'danger': '⚠️', 'dangereux': '⚠️', 'dangereuse': '⚠️',
  'guerre': '⚔️', 'guerres': '⚔️', 'combat': '⚔️', 'combats': '⚔️',
  'paix': '☮️', 'paisible': '☮️', 'paisibles': '☮️',
  'victoire': '🏆', 'victoires': '🏆', 'défaite': '💔', 'défaites': '💔',
  'liberté': '🕊️', 'libre': '🕊️', 'libres': '🕊️',
  'prison': '🔒', 'prisonnier': '🔒', 'prisonnière': '🔒', 'prisonniers': '🔒',
  'force': '💪', 'forces': '💪', 'puissance': '⚡', 'puissant': '⚡',
  'faiblesse': '😔', 'faible': '😔', 'faibles': '😔',
  'courage': '🦁', 'courageux': '🦁', 'courageuse': '🦁',
  'lâche': '🐔', 'lâches': '🐔', 'lâcheté': '🐔',
  'sagesse': '🦉', 'sage': '🦉', 'sages': '🦉',
  'folie': '🌀', 'fou': '🌀', 'folle': '🌀', 'fous': '🌀',
  'rêve': '💭', 'rêves': '💭', 'cauchemar': '😱', 'cauchemars': '😱',
  'secret': '🤫', 'secrets': '🤫', 'secret': '🤫',
  'mensonge': '🤥', 'mensonges': '🤥', 'ment': '🤥', 'mens': '🤥',
  'vérité': '✅', 'vérités': '✅', 'vrai': '✅', 'vraie': '✅', 'vrais': '✅',
  'destin': '🎯', 'hasard': '🎲', 'chance': '🍀', 'malchance': '🌧️',
  'dieu': '✝️', 'dieux': '✝️', 'déesse': '✝️', 'déesses': '✝️',
  'ange': '😇', 'anges': '😇', 'démon': '😈', 'démons': '😈',
  'âme': '👻', 'âmes': '👻', 'esprit': '👻', 'esprits': '👻',

  // ── MUSIQUE & ART ────────────────────────────────────────────────────────
  'musique': '🎵', 'chanson': '🎵', 'chansons': '🎵', 'mélodie': '🎶',
  'instrument': '🎸', 'instruments': '🎸',
  'guitare': '🎸', 'guitares': '🎸', 'piano': '🎹', 'pianos': '🎹',
  'violon': '🎻', 'violons': '🎻', 'trompette': '🎺', 'trompettes': '🎺',
  'tambour': '🥁', 'tambours': '🥁',
  'art': '🎨', 'tableau': '🖼️', 'tableaux': '🖼️', 'peinture': '🎨',
  'sculpture': '🗿', 'sculptures': '🗿',
  'théâtre': '🎭', 'scène': '🎭', 'acteur': '🎭', 'actrice': '🎭',
  'film': '🎬', 'films': '🎬', 'cinéma': '🎬',
  'photo': '📷', 'photos': '📷', 'photographie': '📷',

  // ── SPORTS & JEUX ────────────────────────────────────────────────────────
  'sport': '⚽', 'sports': '⚽', 'foot': '⚽', 'football': '⚽',
  'tennis': '🎾', 'natation': '🏊', 'boxe': '🥊', 'lutte': '🤼',
  'chasse': '🏹', 'pêche': '🎣', 'escalade': '🧗',
  'jeu': '🎮', 'jeux': '🎮',
  'gagne': '🏆', 'gagnes': '🏆', 'gagnons': '🏆', 'gagnez': '🏆', 'gagnent': '🏆',
  'gagnais': '🏆', 'gagnait': '🏆', 'gagner': '🏆', 'gagné': '🏆',
  'perd': '😔', 'perds': '😔', 'perdons': '😔', 'perdez': '😔', 'perdent': '😔',
  'perdais': '😔', 'perdait': '😔', 'perdre': '😔', 'perdu': '😔',

}

// ── Fonction d'application ────────────────────────────────────────────────────
export function applyEmojiMode(text) {
  if (!text) return text

  // Découpe en tokens : mots + ponctuation + espaces
  const tokens = text.split(/(\s+|[.,!?;:«»"'()[\]{}\-–—…])/)

  return tokens.map((token, i) => {
    // Espaces et ponctuations : passer tels quels
    if (/^\s*$/.test(token) || /^[.,!?;:«»"'()[\]{}\-–—…]+$/.test(token)) {
      return token
    }

    // Nettoyer le token : minuscules, sans ponctuation collée
    const clean = token
      .toLowerCase()
      .replace(/^[^a-záàâäéèêëíìîïóòôöúùûüýÿæœç]+/, '')
      .replace(/[^a-záàâäéèêëíìîïóòôöúùûüýÿæœç]+$/, '')

    const emoji = EMOJI_DICT[clean]
    if (emoji) {
      return (
        <span key={i} title={token} style={{ cursor: 'default' }}>
          {emoji}
        </span>
      )
    }

    return token
  })
}

export default EMOJI_DICT
